site_name: Documentations by Rohit Farmer
site_description: Rohit Farmer's cookbook-style documentation website on frequently used software and code snippets.
site_url: https://docs.rohitfarmer.com
site_author: Rohit Farmer
repo_url: https://github.com/rohitfarmer/mk-docs
repo_name: GitHub
docs_dir: contents
site_dir: docs
theme:
  name: material
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: blue grey
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
    #scheme: slate
    #primary: orange
    #accent: indigo
  features:
    - navigation.path
    - navigation.top
    - navigation.tracking    
    - navigation.footer
    - content.code.copy

copyright: Â© 2018-2026 Rohit Farmer. Content licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>
   
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - AI-ML:
      - ai-ml/ollama.md
  - BASH:
      - bash/basic-tutorial.md
  - Bioinformatics:
      - bioinformatics/blast.md
      - bioinformatics/taxonomy.md
  - Containers & Virtual Environments:
      - containers/docker.md
      - containers/mamba-environment.md
      - containers/nvim-singularity.md
      - containers/build-singularity.md
  - Database:
      - database/sqlite.md
      - database/sqlite-where.md
  - Editors:
      - editors/joplin.md
      - editors/nvimr-r-ide.md
  - HPC:
      - hpc/locus.md
      - hpc/skyline.md
  - IRC:
      - irc/irc.md
      - irc/weechat.md
  - Linux:
      - linux/audio-video.md
      - linux/desktop-shortcut.md
      - linux/fail2ban.md
      - linux/file-compression.md
      - linux/find-files.md
      - linux/images.md
      - linux/mini-dlna-server.md
      - linux/mount-drive.md
      - linux/naming-rules.md
      - linux/nginx.md
      - linux/package-management.md
      - linux/rsync.md
      - linux/screen.md
      - linux/system-monitoring.md
      - linux/user-management-permissions.md
      - linux/wget.md
      - linux/xrdp.md
  - Molecular Modelling:
      - molecular-modelling/gromacs.md
  - Python:
      - python/getting-back-to-python.md
      - python/numpy.md
      - python/pandas.md
      - python/matplotlib.md
      - python/environments.md
      - python/web-server.md
  - R:
      - r/data-manipulation.md
      - r/files-folders.md
      - r/machine-learning.md
      - r/non-dataframe-manipulations.md
      - r/parallel-processing.md
      - r/plots.md
      - r/table-html-display.md
  - Remote Access:
      - remote-access/jupyter-ssh-tunneling.md
      - remote-access/ssh-setup.md
  - Tor:
      - tor/tor.md
      - tor/how-to-access-websites-on-the-tor-network.md
  - Uses:
      - uses/general-computing.md
  - Version Control:
      - vcs/git-github.md
  - Writing:
      - writing/capitalization-titles-headings.md
      - writing/lists.md
  - WebRTC:
      - webrtc/jitsi.md
  